"""Routing — pick the model for a role from the EMPIRICAL bakeoff table (not a guess).

Owner 2026-06-05: "auto route are possible also" + "benchmark table for base". The table lives in
_bakeoff/routing.json, GENERATED by _bakeoff/run_bakeoff.py (probes -> rubric -> role->model). This
module is the consumer: the cli/loop asks `pick(role)` and gets the model the bakeoff proved best
for that role, and `provider_for(model)` builds the right wire. ONE source of truth — the agent
routes by measured capability/cost, which is CV-012 (the tier structure) made live + WORLD-02
(reach the cheapest tier that can actually do the work) grounded in evidence.

Roles (per the 2026-06-05 bakeoff): driver, driver_cheap, judge, vision, reason, audit.
  - own-wire roles -> deepseek-chat / grok-build-0.1 / grok-4.3
  - audit/truth -> claude-sonnet-4.6 VIA THE COPILOT BRIDGE (the own-wire pool can't do truth;
    sonnet refused the hallucination probe live). Premium, Pro+ credits — high-stakes calls only.

Degrades safely: if routing.json is missing/unreadable, falls back to sane built-in defaults so a
run never dies for lack of the table.
"""
from __future__ import annotations
import json
from pathlib import Path
from typing import Any

# routing.json lives at <repo>/_bakeoff/routing.json (repo root = parent of this package).
_TABLE_PATH = Path(__file__).resolve().parent.parent.parent / "_bakeoff" / "routing.json"

# Built-in fallback (mirrors the 2026-06-05 bakeoff) so a missing table never breaks a run.
_FALLBACK = {
    "driver":       {"pick": "grok-build-0.1", "fallback": "grok-4.3"},
    "driver_cheap": {"pick": "deepseek-chat"},
    "judge":        {"pick": "deepseek-chat", "fallback": "grok-build-0.1"},
    # ROSTER REALIGNMENT (owner, 2026-06-19): Gemini is the UX-AUTHOR + VISION specialist — its two
    # famous strengths, now a first-class roster tier on the $300 trial. UX is ITERATION-class work
    # (mock→look→polish, many cheap loops), so it must NOT land on the Claude floor (intelligence-class,
    # expensive) — that inversion was the owner's UI/UX blocker. Gemini absorbs the polish loop cheap+fast;
    # Claude keeps the brief + the judgment. Vision moves off grok (it did it as a side capability) onto
    # the specialist. grok-build-0.1 stays the fallback for both (vision-capable, agentic-coding).
    # FALLBACK CHAINS (owner 2026-06-20, the bug-trap fix): a SINGLE fallback is a single point of failure
    # — when gemini-2.5-flash errored, the lone grok fallback was nearly out of credit ($1) and there was
    # no next floor, so seats just died. Every gemini-tier role now falls THROUGH grok TO deepseek-chat,
    # the always-on cheap floor. deepseek is the universal last resort: it must never be the only thing
    # between the council and a dead seat. `fallbacks` (list) is the chain; `fallback` (legacy single) is
    # still read for back-compat by callers that haven't moved to the chain.
    "ux":           {"pick": "gemini-2.5-flash", "fallbacks": ["grok-build-0.1", "deepseek-chat"]},
    "build":        {"pick": "gemini-2.5-flash", "fallbacks": ["grok-build-0.1", "deepseek-chat"]},
    "vision":       {"pick": "gemini-2.5-flash", "fallbacks": ["grok-build-0.1", "deepseek-chat"]},
    "reason":       {"pick": "grok-build-0.1", "fallbacks": ["deepseek-chat", "grok-4.3"]},
    # COUNCIL ON GEMINI (owner, 2026-06-20): the design-council floor moves to Gemini — fast, cheap on
    # the $300 trial, and a capable deliberator (proven live: a 4-seat + chair council on the equip/
    # cross-scope fork ran unanimous on gemini-2.5-flash). Replaces the eos_council (Qwen3-32B rented-GPU)
    # as the DEFAULT council seat model; the council is multi-seat deliberation, not the eos burst tier.
    # eos_council stays reachable by explicit model id for when the rented GPU is the right floor.
    "council":      {"pick": "gemini-2.5-flash", "fallbacks": ["deepseek-chat", "grok-build-0.1"]},
    "audit":        {"pick": "claude-sonnet-4.6", "via": "copilot-bridge",
                     "fallbacks": ["claude-opus-4.8", "deepseek-chat"]},
}

# THE BRIDGE BAKE-OFF (2026-06-06, ECHELON-MCP/bridge_bakeoff.py). The Copilot bridge is a TEXT-ONLY
# wire; REASONING models dump their chain-of-thought inline over it (and truncate before the answer),
# so they are UNUSABLE there even though they're fine direct. The bake-off proved: gpt-5.4-mini is the
# FASTEST clean tier (1.7s); every gpt + claude tier is clean; ONLY the gemini-flash family leaks.
# NOTE: this corrected the wrong hunch "the minis are slow/stale" — the minis are the BEST; the wire
# bug (server never EOFs) was the slowness, fixed in copilot_bridge_client. Blacklist geminis, not minis.
BRIDGE_STALE = {"gemini-3-flash", "gemini-3.5-flash", "gemini-3-flash-preview"}
BRIDGE_DEFAULT = "gpt-5.4-mini"      # fastest clean bridge tier; use for cheap bridge text/reason work


def bridge_safe(model_id: str) -> bool:
    """Is this model usable over the text-only Copilot bridge? (gemini-flash family think-leaks.)"""
    return model_id.lower() not in BRIDGE_STALE


def bridge_pick(requested: str | None = None) -> str:
    """Pick a bridge-safe model: honor `requested` if it's safe, else fall back to the fastest clean
    tier. The agent's `reason` tier-hand routes through this so it can't reach a think-leaking gemini
    over the bridge by naming it."""
    if requested and bridge_safe(requested):
        return requested
    return BRIDGE_DEFAULT


def _load() -> dict[str, Any]:
    try:
        data = json.loads(_TABLE_PATH.read_text(encoding="utf-8"))
        return data.get("roles", {}) or _FALLBACK
    except Exception:
        return _FALLBACK


_ROLES = _load()


def pick(role: str) -> str:
    """The model id the bakeoff chose for this role. Unknown role -> the driver pick (safe default)."""
    r = _ROLES.get(role) or _ROLES.get("driver") or _FALLBACK["driver"]
    return r.get("pick", "grok-build-0.1")


def model_chain(role: str) -> list[str]:
    """The FULL try-order for a role: [pick, *fallbacks] (with the legacy single `fallback` folded in),
    de-duped, order preserved. A caller walks this until one model answers — so no role dies on a single
    floor outage (the bug-trap fix). deepseek-chat anchors the cheap roles as the universal last resort.
    Unknown role -> the driver chain.

    ROSTER WEATHER (owner law 2026-09-01): OpenRouter free seats come and go daily. An OpenRouter
    id ('/' in the id) that a FRESH roster snapshot no longer lists as free is SKIPPED — the chain
    falls through to the next floor instead of 404ing a retired seat. A missing/stale roster has
    no opinion (degrade OPEN); a skip that would empty the chain is refused (the original chain
    beats a dead one).

    SEAT HEALTH (R-0171 unit D, 2026-09-09): a second, lower filter — see [_drop_dead_seats].
    The roster says whether a seat is LISTED; `echelon roster probe` says whether it ANSWERED.
    Same degrade-OPEN rules, but it governs every id, not only the ':free' ones."""
    out = declared_chain(role)
    try:
        from .roster import free_set, is_fresh
        snap_free = free_set()
        if is_fresh() and snap_free:
            # Only ':free'-suffixed ids are OpenRouter roster weather; a bare '<org>/<model>'
            # id rides a DIRECT wire (e.g. NVIDIA's own) and is not roster-governed.
            kept = [m for m in out if not m.endswith(":free") or m in snap_free]
            if kept:
                out = kept
    except Exception:
        pass
    out = _drop_dead_seats(out)
    return out


def _drop_dead_seats(chain: list[str]) -> list[str]:
    """SEAT HEALTH (R-0171 unit D, 2026-09-09): drop an id that a FRESH probe says will
    not usefully answer — the same shape of skip as a retired ':free' id, one floor lower.

    The roster filter above answers 'is this seat LISTED'; this answers 'did this seat
    ANSWER'. They are different facts: on 2026-09-09 five LISTED seats cost a council 408 s
    and two answered. Unlike the roster this governs EVERY id — a bare '<org>/<model>' on a
    direct wire is exactly the seat that hung 302 s.

    Degrades OPEN in both directions: no seat-health file, or one older than an hour, has
    no opinion and nothing is dropped (today's behaviour); and a skip that would empty the
    chain is refused, because the original chain beats a dead one."""
    try:
        from .roster import is_dead, load_health
        snap = load_health()
        if not snap:
            return chain
        kept = [m for m in chain if not is_dead(m, snap)]
        return kept or chain
    except Exception:
        return chain


def via_bridge(role: str) -> bool:
    """Does this role route over the Copilot bridge (premium tier) rather than an own wire?"""
    return (_ROLES.get(role) or {}).get("via") == "copilot-bridge"


def reason_for(role: str) -> str:
    """The table's own 'why' for this role, PLUS any seat the live chain is currently
    skipping. A silent skip is the failure mode the 2026-09-09 trace punished: a caller
    that sees a shorter chain must be able to read WHY it is shorter, from the same door."""
    why = (_ROLES.get(role) or {}).get("why", "")
    skipped = skipped_seats(role)
    if not skipped:
        return why
    notes = "; ".join(f"{m} ({r})" for m, r in skipped)
    return f"{why} [skipping: {notes}]".strip()


def skipped_seats(role: str) -> list[tuple[str, str]]:
    """[(model_id, reason)] for every id the DECLARED chain names but model_chain drops
    right now — the audit trail behind a chain that got shorter. Reasons: 'retired from
    the free roster' (catalogue) or 'seat-health: <what the probe saw>' (live)."""
    declared = declared_chain(role)
    live = set(model_chain(role))
    out: list[tuple[str, str]] = []
    for m in declared:
        if m in live:
            continue
        reason = "retired from the free roster"
        try:
            from .roster import seat_health
            rec = seat_health(m)
            if rec is not None:
                reason = (f"seat-health: {rec.get('error') or 'no answer'}"
                          if not rec.get("answered")
                          else f"seat-health: shape={rec.get('shape')}")
        except Exception:
            pass
        out.append((m, reason))
    return out


def declared_chain(role: str) -> list[str]:
    """The role's try-order as the TABLE declares it — no roster or seat-health filtering.
    model_chain() is this minus whatever today's weather removed."""
    r = _ROLES.get(role) or _ROLES.get("driver") or _FALLBACK["driver"]
    chain = [r.get("pick", "grok-build-0.1")]
    chain += list(r.get("fallbacks", []))
    if r.get("fallback"):
        chain.append(r["fallback"])
    seen, out = set(), []
    for m in chain:
        if m and m not in seen:
            seen.add(m)
            out.append(m)
    return out


def pick_driver_for_size(ctx_chars: int, primary_model: str, alt_model: str,
                         threshold: int) -> str:
    """SIZE-AWARE DRIVER SPLIT (owner 2026-06-06, measured): each model in its fast band — the alt
    (deepseek) drives SMALL/sparse prompts (it's flat-fast there; grok-build over-thinks them), the
    primary (grok-build) drives LARGE structured prompts (fast on big, deepseek slower). Pure
    decision logic, extracted from the loop so it's directly testable: returns which MODEL should
    drive THIS step given its context size. (driver-latency-is-tail-variance.)"""
    return alt_model if ctx_chars < threshold else primary_model


def provider_for(model_id: str, *, prefer_bridge: bool = False):
    """Build the provider that serves `model_id`. ONE place that maps a model id to its wire, so
    the cli/loop never repeats this. claude-*/bridge ids -> BridgeProvider (Copilot, Pro+ credits);
    deepseek* -> DeepSeekProvider; grok* -> GrokProvider. prefer_bridge forces the bridge (for an
    audit role whose model also exists elsewhere)."""
    mid = model_id.lower()
    # gemini-* now has a DIRECT key (AI Studio, .apikey GEMINI=...) → its own OpenAI-compat wire,
    # not the Copilot bridge. The bridge was the fallback when no direct key existed; with one, the
    # direct provider wins (free tier $0, lower latency, no Pro+ credit draw). prefer_bridge still
    # forces the bridge for an audit role whose model also lives there.
    if mid.startswith("gemini") and not prefer_bridge:
        from echelon_engine.atoms.providers.gemini import GeminiProvider
        return GeminiProvider()
    # THE MAX2 SEAT (owner order 2026-09-01: "max2 into the roster") — the second Claude Max
    # subscription as a routable TEXT-ONLY brain via the claude-max2 CLI shim. Flat-rate
    # Sonnet/Opus for gate/judge/council text work; raises (ABSTAINS) on tool calls. Checked
    # BEFORE the prefer_bridge catch: max2 never lives on the bridge, whatever the role prefers.
    if mid.startswith("max2"):
        from echelon_engine.atoms.providers.claude_cli import ClaudeCliProvider
        return ClaudeCliProvider()
    if prefer_bridge or mid.startswith("claude-") or mid.startswith(("gpt-", "gemini-", "oswe", "raptor", "mai-")):
        from echelon_engine.atoms.providers.bridge import BridgeProvider
        return BridgeProvider()
    if mid.startswith("deepseek"):
        from echelon_engine.atoms.providers.deepseek import DeepSeekProvider
        return DeepSeekProvider()
    # OpenRouter free seats (R-0135): ox = the reasoning gate, minimax = the pixel gate.
    # Keyed by OPENROUTER_API_KEY — the factory raises when the key is absent, which is
    # exactly the ABSTAIN a chain-walk needs.
    if mid.startswith(("stealth/", "ox")):
        from echelon_engine.atoms.providers.openai_compat import ox_provider
        return ox_provider()
    if mid.startswith("minimax"):
        from echelon_engine.atoms.providers.openai_compat import minimax_provider
        return minimax_provider()
    if mid.startswith("grok"):
        from echelon_engine.atoms.providers.grok import GrokProvider
        return GrokProvider()
    # nvidia/* WITHOUT the ':free' suffix = NVIDIA's OWN wire (integrate.api.nvidia.com,
    # NVIDIA_API_KEY — owner provisioned 2026-09-01): its free tier with its own rate limits,
    # a separate pool from OpenRouter's. The ':free'-suffixed twin ids stay on OpenRouter.
    if mid.startswith("nvidia/") and not mid.endswith(":free"):
        from echelon_engine.atoms.providers.openai_compat import nemotron_provider
        return nemotron_provider()
    # THE LOCAL FLOOR SEATS (MoE bake-off 2026-09-03, routing intentional-2026-09-03a):
    # these exact ids are served by LM Studio on :19999 — $0, AGENT_SYSTEM-injected. Explicit
    # set, not a prefix rule, so remote '<org>/<model>' ids keep riding NIM/OpenRouter below.
    if mid in ("openai/gpt-oss-20b", "qwen/qwen3-coder-30b", "baidu/ernie-4.5-21b-a3b",
               "smollm3-3b-gabliterated-i1"):
        from echelon_engine.atoms.providers.local import LocalProvider
        return LocalProvider()
    # Any other '<org>/<model>' id: PREFER the NVIDIA NIM wire when its key is present
    # (83 free endpoints incl. deepseek-ai/*, moonshotai/kimi-k3, meta/muse-glimmer —
    # rate limits are the only cost); otherwise the generic OpenRouter wire. ':free'
    # suffix always means OpenRouter (handled above by the roster filter + this branch:
    # OpenRouter accepts the suffixed id, NIM would 404 it and the chain-walk moves on).
    if "/" in mid:
        from echelon_engine.atoms.providers.openai_compat import (nim_provider,
                                                                  openrouter_provider)
        if not mid.endswith(":free"):
            try:
                return nim_provider()   # raises when NVIDIA_API_KEY is absent -> fall through
            except Exception:
                pass
        return openrouter_provider()
    # AMD-T1 = the Qwen3-32B council over the eos reverse tunnel (the FREE capable tier). Routed by the
    # served model id or a friendly alias (eos/council/amd-t1/qwen3). It's a first-class tier now, not a
    # runs/ shim — reachable anywhere provider_for is (brain, reason(), judge, audit, the swarm floor).
    if mid.startswith(("qwen3", "eos", "council", "amd-t1", "amd")):
        from echelon_engine.atoms.providers.eos_council import EosCouncilProvider
        return EosCouncilProvider()
    # Unknown -> try the bridge (its catalog is broadest); the loop will surface an error if absent.
    from echelon_engine.atoms.providers.bridge import BridgeProvider
    return BridgeProvider()
